apiVersion: apps/v1
kind: Deployment
metadata:
  name: regtech-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: regtech-app
  template:
    metadata:
      labels:
        app: regtech-app
    spec:
      containers:
      - name: app-container
        # Use your DockerHub image
        image: olatunjym/regtech-app:latest
        ports:
        - containerPort: 8080
