apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: regtech-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
  - hosts:
      - regtech.example.com  # Placeholder for now
    secretName: tls-secret   # The secret with your TLS cert and key
  rules:
  - host: regtech.example.com  # Placeholder for now
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: regtech-app
            port:
              number: 80
