apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: monitoring
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9090'
spec:
  selector: 
    app: prometheus-server  # Ensure this matches your Prometheus pod/deployment labels
  type: LoadBalancer  
  ports:
    - port: 8080            # Exposing Prometheus on port 8080
      targetPort: 9090       # Prometheus listens on 9090
      nodePort: 30000        # Ensure this port is free and allowed by your cluster's configuration
