name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Authenticate to Google Cloud using the service account key
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    # Set up the gcloud SDK
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    # Install gke-gcloud-auth-plugin
    - name: Install gke-gcloud-auth-plugin
      run: |
        gcloud components install gke-gcloud-auth-plugin
        export USE_GKE_GCLOUD_AUTH_PLUGIN=True

    # Install Terraform
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    - name: Initialize Terraform
      working-directory: ./terraform
      env:
        TF_VAR_gcp_sa_key: ${{ secrets.GCP_SA_KEY }}
      run: terraform init

    # Apply Terraform to create GKE cluster
    - name: Apply Terraform to create GKE cluster
      working-directory: ./terraform
      env:
        TF_VAR_gcp_sa_key: ${{ secrets.GCP_SA_KEY }}
      run: terraform apply -auto-approve -var "project_id=${{ secrets.GCP_PROJECT_ID }}" -var "region=${{ secrets.GCP_REGION }}"

    # Install kubectl
    - name: Install kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'latest'

    # Authenticate gcloud to configure GKE credentials
    - name: Configure GKE credentials
      run: |
        gcloud container clusters get-credentials youverify --zone ${{ secrets.GCP_ZONE }} --project ${{ secrets.GCP_PROJECT_ID }}

    # Deploy to GKE
    - name: Deploy to GKE
      run: |
        kubectl apply -f k8s/deployment.yaml

    # Run tests
    - name: Run tests
      run: |
        kubectl get pods
        # Add any specific test steps here (integration tests, smoke tests, etc.)

    # Rollback on failure
    - name: Rollback on failure
      if: failure()
      run: |
        kubectl rollout undo deployment regtech-app
