name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Updated to latest version

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
        export_default_credentials: true

    - name: Install kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'latest'

    - name: Configure GKE credentials
      run: |
        gcloud container clusters get-credentials my-k8s-cluster --zone ${{ secrets.GCP_ZONE }} --project ${{ secrets.GCP_PROJECT_ID }}

    - name: Deploy to GKE
      run: |
        kubectl apply -f k8s/deployment.yaml

    - name: Run tests
      run: |
        kubectl get pods
        # Add any specific test steps here (integration tests, smoke tests, etc.)

    - name: Rollback on failure
      if: failure()
      run: |
        kubectl rollout undo deployment <deployment-name>
