name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Latest version

    # Authenticate to Google Cloud using the service account key
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    # Set up the gcloud SDK
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    # Initialize Terraform with environment variables
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0  # Set your preferred Terraform version

    - name: Initialize Terraform
      working-directory: ./terraform
      env:
        TF_VAR_gcp_sa_key: ${{ secrets.GCP_SA_KEY }}  # Pass the key as an environment variable
      run: terraform init

    # Plan Terraform changes (this will show what changes will be applied)
    - name: Plan Terraform Changes
      working-directory: ./terraform
      env:
        TF_VAR_gcp_sa_key: ${{ secrets.GCP_SA_KEY }}
      run: terraform plan -var "project_id=${{ secrets.GCP_PROJECT_ID }}" -var "region=${{ secrets.GCP_REGION }}"

    # Apply Terraform if necessary (only apply changes if the plan detects changes)
    - name: Apply Terraform to create GKE cluster
      working-directory: ./terraform
      env:
        TF_VAR_gcp_sa_key: ${{ secrets.GCP_SA_KEY }}
      run: terraform apply -auto-approve -var "project_id=${{ secrets.GCP_PROJECT_ID }}" -var "region=${{ secrets.GCP_REGION }}"

    - name: Install kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'latest'

    # Authenticate gcloud to configure GKE credentials
    - name: Configure GKE credentials
      run: |
        gcloud container clusters get-credentials youverify --zone ${{ secrets.GCP_ZONE }} --project ${{ secrets.GCP_PROJECT_ID }}

    - name: Deploy to GKE
      run: |
        kubectl apply -f k8s/deployment.yaml

    - name: Run tests
      run: |
        kubectl get pods
        # Add any specific test steps here (integration tests, smoke tests, etc.)

    - name: Rollback on failure
      if: failure()
      run: |
        kubectl rollout undo deployment regtech-app
