name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Latest version

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}  # Using the existing secret
        export_default_credentials: true

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0  # Set your preferred Terraform version

    - name: Initialize Terraform
      working-directory: ./terraform  # Adjusted to match your folder structure
      run: terraform init

    - name: Apply Terraform to create GKE cluster
      working-directory: ./terraform  # Adjusted to match your folder structure
      run: terraform apply -auto-approve

    - name: Install kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'latest'

    - name: Configure GKE credentials
      run: |
        gcloud container clusters get-credentials youverify --zone ${{ secrets.GCP_ZONE }} --project ${{ secrets.GCP_PROJECT_ID }}  # GKE cluster name updated

    - name: Deploy to GKE
      run: |
        kubectl apply -f k8s/deployment.yaml

    - name: Run tests
      run: |
        kubectl get pods
        # Add any specific test steps here (integration tests, smoke tests, etc.)

    - name: Rollback on failure
      if: failure()
      run: |
        kubectl rollout undo deployment regtech-app
